### ISSUE TITLE
Get parsley error

### ISSUE THREAD

**Issue by marcosguerrini** [GiriB/django-gentelella#2]
I get this warning and error in every pages that use this gentelella adaptation for django.

> utils.js:87 You must bind Parsley on an existing element.
> warn @ utils.js:87
> 
> Uncaught TypeError: Cannot read property 'isValid' of undefined
>     at validateFront (custom.js:999)
>     at HTMLDocument.<anonymous> (custom.js:975)
>     at i (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at Function.ready (jquery.min.js:2)
>     at HTMLDocument.J (jquery.min.js:2)

even if i use the plain_page.html get that error.

**Comment by anglvictor** [comment]
any updates on this issue?

**Comment by drjmcauliffe** [comment]
Coming back to this after sometime... I fixed this by wrapping the `if-else` block

```
if (true === $('#demo-form2').parsley().isValid()) {
    $('.bs-callout-info').removeClass('hidden');
    $('.bs-callout-warning').addClass('hidden');
} else {
    $('.bs-callout-info').addClass('hidden');
    $('.bs-callout-warning').removeClass('hidden');
}
```
... in an if statement to check `demo-form2` exists in the page, as follows:

```
if ($('#demo-form2').length > 0 ) {
    if (true === $('#demo-form2').parsley().isValid()) {
        $('.bs-callout-info').removeClass('hidden');
        $('.bs-callout-warning').addClass('hidden');
    } else {
        $('.bs-callout-info').addClass('hidden');
        $('.bs-callout-warning').removeClass('hidden');
    }
}
```

No more error!

**Comment by OrangeVulture** [comment]
> Coming back to this after sometime... I fixed this by wrapping the `if-else` block
> 
> ```
> if (true === $('#demo-form2').parsley().isValid()) {
>     $('.bs-callout-info').removeClass('hidden');
>     $('.bs-callout-warning').addClass('hidden');
> } else {
>     $('.bs-callout-info').addClass('hidden');
>     $('.bs-callout-warning').removeClass('hidden');
> }
> ```
> 
> ... in an if statement to check `demo-form2` exists in the page, as follows:
> 
> ```
> if ($('#demo-form2').length > 0 ) {
>     if (true === $('#demo-form2').parsley().isValid()) {
>         $('.bs-callout-info').removeClass('hidden');
>         $('.bs-callout-warning').addClass('hidden');
>     } else {
>         $('.bs-callout-info').addClass('hidden');
>         $('.bs-callout-warning').removeClass('hidden');
>     }
> }
> ```
> 
> No more error!

I am sorry I am a noob. Which file are you talking about?

**Comment by joseph9991** [comment]
Hey guys. The above solution works. Just make sure you delete your cache and then try again.
